AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - kithe.gemspec
    - Rakefile
    - Gemfile
    - bin/rails
    - spec/**/*
    - test/**/*
    - config/**/*


Metrics/LineLength:
  Max: 110

Layout:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false